### ISSUE TITLE
Some files seems to miss to implement the Add on via the amps' method

### ISSUE THREAD

**Issue by AlfrescoNewTest** [Acosix/alfresco-site-hierarchy#2]
Hello

Your great work really interest me. I would like to implement it via the Amps method.

Nethertheless, some files are missing to generate the Add on (or perhaps I haven't seen them). 
I can correctly find the amps of the utility folder("de.acosix.alfresco.utility.repo" and "de.acosix.alfresco.site.hierarchy.repo"), but I don't manage to find the 2 other ones: the hierarchy folder is empty("de.acosix.alfresco.site.hierarchy.share" and "de.acosix.alfresco.site.hierarchy.repo"): only a link to "de.acosix.alfresco.site.hierarchy.parent/" can be found, but there's no snapshot folder, and thus no amps.

Is it possible to put the missing snapshots (with the amps) in the hierarchy folder?
Or is there an other way to get them?

Thanks in advance

**Comment by AFaust** [comment]
The module has been [published to Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22de.acosix.alfresco.site.hierarchy%22) where all the AMPs are available. You do not need to generate the addon yourself.

**Comment by AlfrescoNewTest** [comment]
Thanks for the quick answer!
