### ISSUE TITLE
No Change in Site Properties Dialog Post Installation

### ISSUE THREAD

**Issue by vkaustubh** [Acosix/alfresco-site-hierarchy#6]
Hi!

I'm trying to install this extension for a local copy of Alfresco, installed using the standard binary installer. The binary installer used is 'alfresco-community-installer-201707-linux-x64.bin' and the full version number of the duly installed Alfresco Repo is 'Community - 5.2.0 (re21f2be5-b22)'.

I've attempted the following procedure to get this installed.

* Download acosix utility source code, `mvn install` it. 
* Download the site-hierarchy module and `mvn install` it.
* Copy relevant .amp files to amps/ and amps_share/
* From the bin folder, ./apply_amp.sh
* Restart.

Also, tried building relevant jar files, and placing them in <alfresco-home>/modules/share and <alfresco-home/modules/platform directories.

``
modules
├── platform
│   ├── de.acosix.alfresco.site.hierarchy.repo-1.0.0.2-SNAPSHOT-installable.jar
│   ├── de.acosix.alfresco.utility.common-1.0.3.0-SNAPSHOT.jar
│   └── de.acosix.alfresco.utility.repo-1.0.3.0-SNAPSHOT-installable.jar
└── share
    ├── de.acosix.alfresco.site.hierarchy.share-1.0.0.2-SNAPSHOT-installable.jar
    ├── de.acosix.alfresco.utility.common-1.0.3.0-SNAPSHOT.jar
    └── de.acosix.alfresco.utility.share-1.0.3.0-SNAPSHOT-installable.jar

``

Also tried putting above jars in `<alfresco-home>/tomcat/webapps/alfresco/WEB-INF/lib` and `tomcat/webapps/share/WEB-INF/lib`.

The end result is the same.

* Customizing user dashboard detects a new dashlet called 'Hierarchy Dashlet'. It starts by being completely blank. When you edit the properties of this dashlet, it asks 'Top level site for hierarchy tree' and only one may be selected. This seems to suggest that there can be only one parent site and everything else must be a child. However, the screenshot suggests you can have any number of root sites.

* Most importantly, clicking 'Create Site' gives no custom input forms such as "Parent Site" etc. In other words, nothing changes.

I tried going into `<alfresco-home>/tomcat/shared/classes` and created a file called `share-global.properties` with the line `acosix-site-hierarchy.siteManagementExtension.enabled = true`, restarted Alfresco but still no effect.

Also, compared to the screenshot of the Create Site form in your repository here on Github, there is one thing I notice which is different. In my installation of Alfresco, by default, the "Create Site" interface shows a "Type" form field which has only one option "Collaboration Site". Could there be a conflict between the two?

So, what am I missing here? Is there an additional step I am not including? Do I need to edit some properties? Or does this plugin mandate a more detailed reconstruction of the Alfresco WAR itself (I hope not)? I'd be grateful if you could point me in the right direction.

**Comment by AFaust** [comment]
In Alfresco 5.2 the Create Site / Edit SIte dialogs have - by default - been replaced by new Aikau-based dialogs. Unfortunately, there is an issue with these dialogs that make extending them impossible without causing side effects, and Alfresco has decided not to fix that issue.. The problem is described in #1, my comments to [this Alfresco blog post](https://community.alfresco.com/community/ecm/blog/2016/11/23/create-and-edit-site-customization) and the [Alfresco JIRA ticket ALF-21855](https://issues.alfresco.com/jira/browse/ALF-21855).

In order to use this addon in 5.2, you have to either re-enable the legacy dialogs or explicitly activate the 5.2 Surf Extension Module (via the /share/page/modules/deploy tool). If you choose the latter, beware that any features using the TinyMCE editor in any Share page may not work correctly.

**Comment by vkaustubh** [comment]
That helped!

Edited `./tomcat/webapps/share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/share/imports/share-header.lib.js`, on line 1534. Restarted Alfresco and the menu appears as expected.

Since yours is the first and most crucial extension for our use case, I will ensure this flag is set to false for all other extension work we are doing. We expect to add some custom workflows, document actions and metadata. I believe the above option set to true should be fine for these customizations.

If we do have to make customized menus and dashlets, I guess we will have to ensure we don't use Aikau based dialogs. 

Thank you so much for your help. I'll close this issue.
